#define _USE_LIVE_VIDEO

#define MAX_CORNERS 500

#define VIDEO_WIDTH			320
#define VIDEO_INVWIDTH		1/VIDEO_WIDTH
#define VIDEO_HEIGHT		240
#define VIDEO_INVHEIGHT		1/VIDEO_HEIGHT
#define VIDEO_ASPECT		VIDEO_WIDTH/VIDEO_HEIGHT
#define VIDEO_SIZE			VIDEO_WIDTH,VIDEO_HEIGHT
